
name: Run tests

on: [push, pull_request]

jobs:
  test_micropython:
    runs-on: ubuntu-latest
    env:
      MICROPYTHON_BIN: ./micropython/ports/unix/build-standard/micropython
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: micropython/micropython
        path: micropython
        ref: master
    - name: Setup MicroPython X86
      working-directory: micropython
      run: source tools/ci.sh && ci_unix_32bit_setup && ci_unix_standard_build

    - name: Run tests
      run: |
        MICROPYPATH=./ ${{ env.MICROPYTHON_BIN }} tests/test_npyfile.py

  test_cpython:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: '3.10'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: |
        PYTHONPATH=./ python tests/test_npyfile.py
